
version: 0.2
env:
  variables:
    MIX_PUSHER_FORCE_TLS: true
    MIX_PUSHER_ENCRYPTED: true
    MIX_WS_PORT: 443
  parameter-store:
    MIX_RECAPTCHAV3_SITEKEY: "/build/deep-link/master/GetUri/mixRecaptchaV3SiteKey"
    MIX_PUSHER_APP_ID: "/build/deep-link/master/GetUri/mixPusherAppId"
    MIX_PUSHER_APP_KEY: "/build/deep-link/master/GetUri/mixPusherAppKey"
    MIX_PUSHER_APP_HOST: "/build/deep-link/master/GetUri/mixPusherAppHost"
    MIX_WS_HOST: "/build/deep-link/master/GetUri/mixWsHost"
    FONTAWESOME_NPM_AUTH_TOKEN: "/build/deep-link/master/GetUri/fontawesomeNpmAuthToken"
phases:
  install:
    # run-as: root
    commands:
      - npm -v
      - npm install
  build:
    commands:
      - npm run prod2
artifacts:
  # base-directory: /var/www/allfans.com/
  # name: build-artifact-name
  # discard-paths: no
  files:
    - '**/*'
  exclude-paths:
    - ./**/node_modules
    - ./**/resources/assets
    - ./**/rsyncconfig
    - ./**/.vscode
    - ./**/data.ms

