<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'UpdateHelper\\' => array($vendorDir . '/kylekatarnls/update-helper/src'),
    'Twig_' => array($vendorDir . '/twig/twig/lib'),
    'Parsedown' => array($vendorDir . '/erusev/parsedown'),
    'Mockery' => array($vendorDir . '/mockery/mockery/library'),
    'LinkPreview' => array($vendorDir . '/kasp3r/link-preview/src'),
    'Laracasts\\Flash' => array($vendorDir . '/laracasts/flash/src'),
    'Jlapp\\Swaggervel' => array($vendorDir . '/jlapp/swaggervel/src'),
    'HTMLPurifier' => array($vendorDir . '/ezyang/htmlpurifier/library'),
);
